FROM labordigital/bitbucket-pipeline-images:node-14-environment

LABEL description="Labor Digital Bitbucket Pipes: Node 14 Environment"

# Use bash as our default shell
SHELL ["/bin/bash", "-c"]

ENTRYPOINT ["/opt/npm-run-script.sh build"]