FROM node:8.12

MAINTAINER LABOR digital <info@labor.digital>

LABEL description="Labor Digital Bitbucket Pipelines: NPM Run Build"

COPY npm-run-build.sh /opt/npm-run-build.sh
RUN chmod +x /opt/npm-run-build.sh