/*
 * Copyright 2026 LABOR.digital
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Last modified: 2026.06.24 at 11:06
 */

import type {
	Reporter, FullConfig, Suite, TestCase, TestResult, FullResult
} from '@playwright/test/reporter';
import * as fs from 'fs';

class PipesReporter implements Reporter {
	constructor(options: { customOption?: string } = {}) {
	}
	
	onBegin(config: FullConfig, suite: Suite) {
	}
	
	onTestBegin(test: TestCase) {
	}
	
	onTestEnd(test: TestCase, result: TestResult) {
	}
	
	async onEnd(result: FullResult) {
		try {
			if (!process.env.BITBUCKET_REPO_OWNER || !process.env.BITBUCKET_REPO_SLUG || !process.env.BITBUCKET_COMMIT) {
				console.log("We're not running in bitbucket pipelines, so we skip reporting.");
				return;
			}
			
			const testResultsJson = JSON.parse(fs.readFileSync(process.env.TEST_ROOT_DIR + '/test-reports/results.json').toString());
			let data = {
				"title": "Playwright Image Snapshot Testing",
				"details": "This report is auto generated by our Playwright Image Snapshot Testing pipe.",
				"report_type": "TEST",
				"reporter": "playwright-snapshots",
				"result": testResultsJson.stats.skipped == 0 && testResultsJson.stats.unexpected == 0 && testResultsJson.stats.flaky == 0 ? "PASSED" : "FAILED",
				"data": [
					{
						"title": "Duration",
						"type": "DURATION",
						"value": testResultsJson.stats.duration
					},
					{
						"title": "Test count",
						"type": "NUMBER",
						"value": testResultsJson.stats.expected + testResultsJson.stats.skipped + testResultsJson.stats.unexpected + testResultsJson.stats.flaky
					},
					{
						"title": "Tests passed",
						"type": "NUMBER",
						"value": testResultsJson.stats.expected
					},
					{
						"title": "Tests failed",
						"type": "NUMBER",
						"value": testResultsJson.stats.skipped + testResultsJson.stats.unexpected + testResultsJson.stats.flaky
					}
				]
			};
			
			const url = "https://api.bitbucket.org/2.0/repositories/"+process.env.BITBUCKET_REPO_OWNER+"/"+process.env.BITBUCKET_REPO_SLUG+"/commit/"+process.env.BITBUCKET_COMMIT+"/reports/jest-snapshots-001";
			const response = await fetch(url, {
				method: 'PUT',
				headers: {
					"Content-Type": "application/json",
					'Authorization': 'Basic ' + btoa(process.env.BITBUCKET_DEFAULT_BOT_USER_EMAIL+':'+process.env.BITBUCKET_DEFAULT_BOT_TOKEN)
				},
				body: JSON.stringify(data),
			});
			if (!response.ok) {
				throw new Error(`Response status: ${response.status}`);
			}
			
			const json = await response.json();
		} catch (error) {
			console.log("Error in teardown, but we will not throw an error, because the tests should be responsible of the exit code: ", error.message);
		}
	}
}
export default PipesReporter;
