name: Build and Push - All

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - master

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # build-docker-and-push-ecr
      - name: Build and push build-docker-and-push-ecr
        run: |
          cd build-docker-and-push-ecr
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:build-docker-and-push-ecr
          docker push labordigital/bitbucket-pipeline-images:build-docker-and-push-ecr

      # composer-install
      - name: Build and push composer-install
        run: |
          cd composer-install
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:composer-install
          docker push labordigital/bitbucket-pipeline-images:composer-install
        
      # composer-2-install
      - name: Build and push composer-2-install
        run: |
          cd composer-2-install
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:composer-2-install
          docker push labordigital/bitbucket-pipeline-images:composer-2-install

      # conventional-release
      - name: Build and push conventional-release
        run: |
          cd conventional-release
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:conventional-release
          docker push labordigital/bitbucket-pipeline-images:conventional-release

      # deploy-docker-to-ecs
      - name: Build and push deploy-docker-to-ecs
        run: |
          cd deploy-docker-to-ecs
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:deploy-docker-to-ecs
          docker push labordigital/bitbucket-pipeline-images:deploy-docker-to-ecs

      # deployment-tools
      - name: Build and push deployment-tools
        run: |
          cd deployment-tools
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:deployment-tools
          docker push labordigital/bitbucket-pipeline-images:deployment-tools
  
      # deploy-docker-to-compose-host
      - name: Build and push deploy-docker-to-compose-host
        run: |
          cd deploy-docker-to-compose-host
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:deploy-docker-to-compose-host
          docker push labordigital/bitbucket-pipeline-images:deploy-docker-to-compose-host

      # deploy-via-update-cloudformation-parameter
      - name: Build and push deploy-via-update-cloudformation-parameter
        run: |
          cd deploy-via-update-cloudformation-parameter
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:deploy-via-update-cloudformation-parameter
          docker push labordigital/bitbucket-pipeline-images:deploy-via-update-cloudformation-parameter

      # inject-aws-ecs-startup-script
      - name: Build and push inject-aws-ecs-startup-script
        run: |
          cd inject-aws-ecs-startup-script
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:inject-aws-ecs-startup-script
          docker push labordigital/bitbucket-pipeline-images:inject-aws-ecs-startup-script
  
      # node-environment
      - name: Build and push node-environment
        run: |
          cd node-environment
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:node-environment
          docker push labordigital/bitbucket-pipeline-images:node-environment
      - name: Build and push node-12-environment
        run: |
          cd node-12-environment
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:node-12-environment
          docker push labordigital/bitbucket-pipeline-images:node-12-environment
      - name: Build and push node-14-environment
        run: |
          cd node-14-environment
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:node-14-environment
          docker push labordigital/bitbucket-pipeline-images:node-14-environment
        
      # npm-run-build
      - name: Build and push npm-run-build
        run: |
          cd npm-run-build
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:npm-run-build
          docker push labordigital/bitbucket-pipeline-images:npm-run-build

      # sentry-release
      - name: Build and push sentry-release
        run: |
          cd sentry-release
          docker build . --file Dockerfile --tag labordigital/bitbucket-pipeline-images:sentry-release
          docker push labordigital/bitbucket-pipeline-images:sentry-release