name: Build and Push - All

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - master

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # playwright-1.5.1
      - name: Build and push playwright-1.5.1
        uses: docker/build-push-action@v5
        with:
          context: ./playwright-1.5.1/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:playwright-1.5.1
          platforms: linux/amd64,linux/arm64
          file: ./playwright-1.5.1/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push playwright-1.5.1-pipe
        uses: docker/build-push-action@v5
        with:
          context: ./playwright-1.5.1/.pipe/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:playwright-1.5.1-pipe
          platforms: linux/amd64,linux/arm64
          file: ./playwright-1.5.1/.pipe/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # jest-puppeteer-node20
      - name: Build and push jest-puppeteer-node20
        uses: docker/build-push-action@v5
        with:
          context: ./jest-puppeteer-node20/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:jest-puppeteer-node20
          platforms: linux/amd64,linux/arm64
          file: ./jest-puppeteer-node20/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push jest-puppeteer-node20-pipe
        uses: docker/build-push-action@v5
        with:
          context: ./jest-puppeteer-node20/.pipe/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:jest-puppeteer-node20-pipe
          platforms: linux/amd64,linux/arm64
          file: ./jest-puppeteer-node20/.pipe/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # node-environment
#      - name: Build and push node-14-environment
#        uses: docker/build-push-action@v5
#        with:
#          context: ./node-14-environment/.
#          push: true
#          tags: labordigital/bitbucket-pipeline-images:node-14-environment
#          platforms: linux/amd64,linux/arm64
#          file: ./node-14-environment/Dockerfile
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#      - name: Build and push node-16-environment
#        uses: docker/build-push-action@v5
#        with:
#          context: ./node-16-environment/.
#          push: true
#          tags: labordigital/bitbucket-pipeline-images:node-16-environment
#          platforms: linux/amd64,linux/arm64
#          file: ./node-16-environment/Dockerfile
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
      - name: Build and push node-18-environment
        uses: docker/build-push-action@v5
        with:
          context: ./node-18-environment/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:node-18-environment
          platforms: linux/amd64,linux/arm64
          file: ./node-18-environment/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push node-20-environment
        uses: docker/build-push-action@v5
        with:
          context: ./node-20-environment/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:node-20-environment
          platforms: linux/amd64,linux/arm64
          file: ./node-20-environment/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push node-22-environment
        uses: docker/build-push-action@v5
        with:
          context: ./node-22-environment/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:node-22-environment
          platforms: linux/amd64,linux/arm64
          file: ./node-22-environment/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # conventional-release
      - name: Build and push conventional-release
        uses: docker/build-push-action@v5
        with:
          context: ./conventional-release/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:conventional-release
          platforms: linux/amd64,linux/arm64
          file: ./conventional-release/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # build-docker-and-push-ecr
      - name: Build and push build-docker-and-push-ecr
        uses: docker/build-push-action@v5
        with:
          context: ./build-docker-and-push-ecr/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:build-docker-and-push-ecr
          platforms: linux/amd64,linux/arm64
          file: ./build-docker-and-push-ecr/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # test-environment
      - name: Build and push test-environment
        uses: docker/build-push-action@v5
        with:
          context: ./test-environment/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:test-environment
          platforms: linux/amd64,linux/arm64
          file: ./test-environment/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # composer-2-install
      - name: Build and push composer-2-install
        uses: docker/build-push-action@v5
        with:
          context: ./composer-2-install/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:composer-2-install
          platforms: linux/amd64,linux/arm64
          file: ./composer-2-install/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # composer-install
      - name: Build and push composer-install
        uses: docker/build-push-action@v5
        with:
          context: ./composer-install/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:composer-install
          platforms: linux/amd64,linux/arm64
          file: ./composer-install/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # deploy-docker-to-compose-host
      - name: Build and push deploy-docker-to-compose-host
        uses: docker/build-push-action@v5
        with:
          context: ./deploy-docker-to-compose-host/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:deploy-docker-to-compose-host
          platforms: linux/amd64,linux/arm64
          file: ./deploy-docker-to-compose-host/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # deploy-docker-to-ecs
      - name: Build and push deploy-docker-to-ecs
        uses: docker/build-push-action@v5
        with:
          context: ./deploy-docker-to-ecs/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:deploy-docker-to-ecs
          platforms: linux/amd64,linux/arm64
          file: ./deploy-docker-to-ecs/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # deployment-tools
      - name: Build and push deployment-tools
        uses: docker/build-push-action@v5
        with:
          context: ./deployment-tools/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:deployment-tools
          platforms: linux/amd64,linux/arm64
          file: ./deployment-tools/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
        
      # npm-run-build
      - name: Build and push npm-run-build
        uses: docker/build-push-action@v5
        with:
          context: ./npm-run-build/.
          push: true
          tags: labordigital/bitbucket-pipeline-images:npm-run-build
          platforms: linux/amd64,linux/arm64
          file: ./npm-run-build/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
